In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [ ]:
# creating path for data import

path = r'C:\Users\scott\Desktop\Data Analysis\CF Immersive\Python\Jan-2022 Instacart Basket Analysis'

In [ ]:
# importing sample (10%) dataset

df = pd.read_pickle(os.path.join(path,'02 Data', 'Prepared Data', 'sample_jan_27.pkl'))

### 5a. Behavioral customer profiles

#### Profiles:
- (MS) Morning shopper majority orders from 05:00 - 12:00
- (AS) Afternoon shopper majority orders from 12:00 - 17:00
- (ES) Evening shopper majority orders from 17:00 - 21:00
- (NS) Night shopper majority orders from 21:00 - 05:00

In [115]:
# checking entire sample output

df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,STATE,Age,date_joined,n_dependants,fam_status,income,cust_merge,Region,Activity,Profile
19161827,2177719,163580,7,friday,17,17.0,34358,4,1,Garlic,...,Nevada,22,11/28/2018,1,married,88007,both,West,high,(MP)(YA)(MI)
25249022,1214704,36655,11,saturday,16,5.0,37385,2,0,Organic Red Kale,...,Mississippi,75,1/26/2020,1,married,99412,both,South,high,(MP)(E)(MI)
16782168,2036201,53789,5,saturday,8,8.0,44292,11,0,Premium Unsweetened Iced Tea,...,Michigan,76,5/8/2018,3,married,119825,both,Midwest,high,(MP)(E)(MI)
13672545,903704,167015,18,tuesday,23,3.0,40545,3,1,Berry Medley,...,South Carolina,68,10/5/2019,0,divorced/widowed,130037,both,South,high,(SNC)(E)(HI)
21530846,3249360,161467,46,sunday,10,2.0,21903,16,1,Organic Baby Spinach,...,Alabama,73,6/3/2018,1,married,98692,both,South,high,(MP)(E)(MI)

#### Creating column of mean hour by user_id

In [124]:
# creating new dataframe that includes max hour, user_id, and grouped order_id

df_order_hour = df.groupby(['order_id','user_id'])['order_hour_of_day'].max().reset_index()

In [125]:
# checking df_order_hour

df_order_hour

         order_id  user_id  order_hour_of_day
0               2   202279                  9
1               5   156122                 16
2               6    22352                 12
3               7   142903                 14
4              10   135442                  8
...           ...      ...                ...
1739139   3421061   188776                  8
1739140   3421068     7370                 16
1739141   3421074   167185                  8
1739142   3421076   193225                 13
1739143   3421083    25247                  6

[1739144 rows x 3 columns]

In [133]:
# now grouping df_order_hour by user_id

df_order_hour = df.groupby(['user_id'])[['order_hour_of_day']].mean()

In [139]:
# checking df_order_hour

df_order_hour

         order_hour_of_day
user_id
1                 8.500000
2                10.133333
3                15.800000
4                12.000000
7                14.052632
...                    ...
206203           14.000000
206206           17.093750
206207           12.040000
206208           14.968254
206209           12.882353

[160172 rows x 1 columns]

In [141]:
# turning df_order_hour into dictionary and selecting only key (hour_profile)

df_order_hour.to_dict()['order_hour_of_day']

{1: 8.5,
 2: 10.133333333333333,
 3: 15.8,
 4: 12.0,
 7: 14.052631578947368,
 10: 17.642857142857142,
 11: 10.555555555555555,
 12: 9.0,
 13: 16.5,
 14: 7.636363636363637,
 15: 10.5,
 16: 17.0,
 17: 13.0,
 18: 18.0,
 19: 14.115384615384615,
 21: 10.61111111111111,
 22: 11.625,
 24: 13.5,
 26: 13.833333333333334,
 27: 11.885714285714286,
 28: 14.666666666666666,
 29: 10.761904761904763,
 31: 11.0,
 32: 14.125,
 34: 14.666666666666666,
 35: 15.352941176470589,
 36: 14.291666666666666,
 37: 13.764705882352942,
 38: 11.416666666666666,
 39: 14.235294117647058,
 40: 9.6,
 41: 15.7,
 42: 11.538461538461538,
 43: 13.4,
 46: 14.2,
 47: 16.0,
 48: 13.3,
 49: 13.6,
 50: 11.117647058823529,
 52: 10.8,
 54: 12.098360655737705,
 55: 13.333333333333334,
 56: 11.928571428571429,
 57: 5.0,
 58: 12.222222222222221,
 59: 12.125,
 60: 17.272727272727273,
 62: 12.277777777777779,
 63: 12.91044776119403,
 64: 15.866666666666667,
 65: 11.055555555555555,
 66: 11.5,
 67: 12.5,
 68: 11.5,
 69: 14.0,
 70: 17.636363636363637,
 71: 13.346938775510203,
 72: 14.714285714285714,
 73: 16.5,
 74: 9.11111111111111,
 75: 13.36,
 76: 10.0,
 77: 11.705882352941176,
 78: 12.0,
 79: 11.454545454545455,
 80: 11.666666666666666,
 82: 11.4,
 83: 15.666666666666666,
 84: 11.75,
 85: 14.0,
 86: 14.25925925925926,
 87: 11.68421052631579,
 88: 8.0,
 89: 14.333333333333334,
 90: 12.278688524590164,
 91: 11.777777777777779,
 92: 13.0,
 93: 11.4,
 94: 17.11111111111111,
 95: 13.636363636363637,
 96: 10.6,
 97: 12.5,
 98: 15.0,
 99: 14.357142857142858,
 100: 18.5,
 101: 15.666666666666666,
 102: 16.2,
 103: 16.2,
 104: 9.0,
 107: 17.083333333333332,
 108: 15.0,
 109: 9.0,
 110: 12.34375,
 111: 12.0,
 112: 13.5,
 115: 15.833333333333334,
 116: 14.0,
 117: 13.25,
 118: 9.055555555555555,
 121: 13.571428571428571,
 122: 13.181818181818182,
 123: 14.0,
 124: 10.0,
 125: 10.277777777777779,
 126: 11.25,
 127: 16.28,
 128: 12.6,
 129: 16.625,
 131: 10.166666666666666,
 132: 10.428571428571429,
 133: 9.869565217391305,
 137: 15.2,
 138: 13.076923076923077,
 140: 14.027027027027026,
 142: 14.743589743589743,
 143: 13.842105263157896,
 144: 17.0,
 145: 10.5,
 146: 13.0,
 147: 14.0,
 148: 13.090909090909092,
 149: 15.448275862068966,
 150: 12.35897435897436,
 151: 14.533333333333333,
 152: 13.233333333333333,
 153: 16.545454545454547,
 154: 14.703125,
 155: 9.772727272727273,
 158: 11.8,
 160: 10.727272727272727,
 161: 17.0,
 162: 14.583333333333334,
 163: 15.375,
 164: 10.461538461538462,
 165: 13.5,
 166: 13.5,
 167: 12.714285714285714,
 168: 13.590909090909092,
 169: 14.272727272727273,
 171: 14.0,
 172: 10.75,
 173: 11.5,
 174: 15.235294117647058,
 175: 13.823529411764707,
 176: 13.75,
 177: 6.333333333333333,
 178: 15.166666666666666,
 179: 11.75,
 180: 9.928571428571429,
 181: 15.363636363636363,
 182: 14.277777777777779,
 184: 13.76923076923077,
 185: 10.333333333333334,
 186: 12.666666666666666,
 187: 13.818181818181818,
 188: 11.222222222222221,
 189: 16.75,
 190: 14.176470588235293,
 192: 12.25,
 193: 10.2,
 194: 12.0,
 195: 13.8,
 197: 14.304347826086957,
 198: 17.6,
 200: 14.428571428571429,
 201: 11.6,
 202: 12.526315789473685,
 204: 15.033898305084746,
 205: 15.75,
 206: 13.666666666666666,
 208: 13.25,
 209: 14.434782608695652,
 210: 13.798657718120806,
 212: 15.666666666666666,
 213: 10.4,
 214: 16.127659574468087,
 215: 9.0,
 216: 15.678571428571429,
 217: 10.166666666666666,
 219: 15.19047619047619,
 220: 12.833333333333334,
 221: 13.875,
 222: 8.382978723404255,
 223: 8.725806451612904,
 225: 11.166666666666666,
 226: 12.32,
 227: 14.982142857142858,
 229: 11.444444444444445,
 230: 13.857142857142858,
 232: 11.102564102564102,
 233: 10.82,
 234: 15.411764705882353,
 235: 13.625,
 236: 12.88888888888889,
 237: 10.416666666666666,
 238: 15.411764705882353,
 239: 10.5,
 240: 7.5,
 241: 14.090909090909092,
 242: 18.166666666666668,
 243: 13.636363636363637,
 244: 14.0,
 245: 13.75,
 246: 12.0,
 247: 16.0,
 248: 14.390243902439025,
 249: 19.0,
 250: 14.818181818181818,
 251: 11.0,
 254: 13.625,
 256: 16.0,
 257: 14.533333333333333,
 258: 16.035714285714285,
 260: 10.166666666666666,
 261: 16.166666666666668,
 262: 13.13888888888889,
 264: 12.097222222222221,
 265: 11.5,
 266: 14.0,
 267: 12.675675675675675,
 268: 10.5,
 270: 12.333333333333334,
 271: 14.0,
 272: 15.428571428571429,
 273: 16.142857142857142,
 274: 12.666666666666666,
 275: 15.8125,
 276: 15.25,
 278: 12.523809523809524,
 279: 15.5,
 280: 17.64,
 281: 13.8,
 283: 8.25,
 284: 12.192307692307692,
 287: 11.666666666666666,
 289: 13.212121212121213,
 290: 11.44,
 292: 15.411764705882353,
 293: 18.5,
 294: 9.285714285714286,
 295: 14.2,
 296: 15.333333333333334,
 297: 16.666666666666668,
 299: 11.375,
 300: 14.681818181818182,
 301: 14.615384615384615,
 302: 14.0,
 303: 11.0,
 304: 17.105263157894736,
 306: 11.923076923076923,
 307: 11.958333333333334,
 309: 11.516129032258064,
 310: 11.489795918367347,
 311: 12.4,
 313: 9.1875,
 316: 12.0,
 319: 10.0,
 320: 14.0,
 321: 16.444444444444443,
 322: 16.866666666666667,
 323: 13.80188679245283,
 324: 13.11111111111111,
 325: 11.333333333333334,
 326: 12.75,
 327: 10.757575757575758,
 328: 12.416666666666666,
 329: 17.5,
 330: 15.0,
 331: 17.75,
 332: 19.76923076923077,
 333: 13.166666666666666,
 334: 14.67,
 335: 17.0,
 336: 7.0,
 337: 21.16,
 338: 12.0,
 340: 12.666666666666666,
 341: 12.11111111111111,
 342: 10.777777777777779,
 344: 13.4,
 346: 15.2,
 348: 10.875,
 349: 8.0,
 350: 14.944444444444445,
 351: 12.357142857142858,
 352: 14.11111111111111,
 353: 11.4,
 355: 12.636363636363637,
 357: 12.4,
 358: 12.5,
 359: 15.705882352941176,
 361: 12.076923076923077,
 362: 14.6,
 363: 13.428571428571429,
 364: 14.454545454545455,
 365: 14.0,
 369: 18.72222222222222,
 370: 10.954545454545455,
 372: 17.0,
 373: 15.257142857142858,
 374: 8.0,
 375: 14.4,
 376: 15.6,
 378: 14.666666666666666,
 379: 11.173913043478262,
 380: 13.0,
 381: 15.222222222222221,
 382: 13.619047619047619,
 383: 10.5,
 384: 11.5,
 387: 11.5,
 388: 8.5,
 389: 14.4375,
 390: 16.08823529411765,
 391: 14.0,
 392: 13.0,
 393: 12.842105263157896,
 394: 14.095238095238095,
 396: 14.46875,
 398: 11.925,
 400: 16.8,
 403: 14.795454545454545,
 404: 12.0,
 405: 12.0,
 409: 13.755102040816327,
 410: 16.155172413793103,
 411: 18.0,
 413: 12.095238095238095,
 415: 18.166666666666668,
 417: 14.142857142857142,
 418: 16.529411764705884,
 419: 12.0,
 420: 13.68421052631579,
 422: 13.590909090909092,
 423: 10.555555555555555,
 425: 14.8,
 426: 10.8,
 427: 16.25,
 429: 15.666666666666666,
 430: 14.636363636363637,
 431: 8.0,
 432: 16.17948717948718,
 433: 14.666666666666666,
 435: 17.294117647058822,
 436: 10.333333333333334,
 437: 11.933333333333334,
 438: 16.55,
 439: 15.0,
 440: 11.625,
 441: 13.75,
 442: 13.294117647058824,
 443: 17.714285714285715,
 444: 16.194174757281555,
 446: 13.0,
 447: 11.5,
 448: 14.227272727272727,
 449: 16.666666666666668,
 450: 12.2,
 451: 11.74074074074074,
 452: 15.73913043478261,
 453: 11.0,
 454: 14.907894736842104,
 455: 10.444444444444445,
 456: 15.75,
 458: 11.117647058823529,
 459: 12.411764705882353,
 462: 13.51968503937008,
 463: 12.0,
 464: 12.953488372093023,
 465: 14.895833333333334,
 466: 14.365079365079366,
 467: 9.5,
 468: 14.0,
 469: 13.666666666666666,
 470: 13.0,
 471: 12.0,
 473: 9.631578947368421,
 474: 15.090909090909092,
 475: 10.7,
 476: 12.333333333333334,
 478: 18.0,
 479: 16.58823529411765,
 480: 13.75,
 481: 17.146341463414632,
 482: 15.0,
 483: 9.0,
 484: 16.0,
 485: 12.944444444444445,
 486: 13.68,
 487: 13.422222222222222,
 488: 12.555555555555555,
 489: 14.833333333333334,
 492: 19.0,
 493: 12.428571428571429,
 495: 15.32,
 496: 14.340425531914894,
 497: 11.894736842105264,
 498: 18.142857142857142,
 499: 18.0,
 501: 14.5,
 502: 12.4,
 503: 15.807692307692308,
 507: 13.222222222222221,
 508: 13.391304347826088,
 509: 11.11111111111111,
 510: 10.6,
 511: 17.666666666666668,
 515: 11.0,
 516: 13.135416666666666,
 518: 8.75,
 519: 11.666666666666666,
 520: 15.62962962962963,
 522: 18.5,
 523: 12.6,
 524: 8.6,
 525: 9.470588235294118,
 528: 13.661016949152541,
 529: 13.0625,
 531: 12.823529411764707,
 534: 7.0,
 535: 12.75,
 537: 9.6,
 538: 14.421052631578947,
 539: 15.777777777777779,
 540: 13.5,
 541: 13.0,
 543: 13.7,
 546: 17.0,
 547: 12.777777777777779,
 548: 9.555555555555555,
 549: 16.555555555555557,
 551: 10.666666666666666,
 552: 13.166666666666666,
 553: 15.75,
 554: 15.545454545454545,
 555: 12.727272727272727,
 557: 11.333333333333334,
 558: 12.852941176470589,
 559: 14.590909090909092,
 560: 11.294117647058824,
 562: 11.555555555555555,
 563: 15.0,
 564: 13.952380952380953,
 565: 16.0,
 566: 12.0,
 567: 14.911764705882353,
 568: 16.857142857142858,
 570: 15.0,
 571: 16.0,
 573: 11.818181818181818,
 574: 14.333333333333334,
 576: 13.2,
 577: 17.666666666666668,
 580: 12.166666666666666,
 582: 14.916666666666666,
 583: 13.783333333333333,
 584: 16.0,
 585: 15.833333333333334,
 587: 12.142857142857142,
 588: 11.95,
 591: 12.0,
 593: 11.0,
 595: 8.375,
 596: 16.058823529411764,
 597: 16.714285714285715,
 598: 12.0,
 599: 15.714285714285714,
 600: 11.9,
 601: 13.666666666666666,
 602: 17.75,
 603: 15.666666666666666,
 604: 11.657142857142857,
 605: 13.666666666666666,
 606: 14.375,
 607: 15.266666666666667,
 608: 10.6,
 609: 14.727272727272727,
 611: 15.090909090909092,
 612: 11.705882352941176,
 613: 11.733333333333333,
 616: 14.15625,
 617: 18.666666666666668,
 618: 13.137254901960784,
 620: 18.0,
 622: 15.166666666666666,
 623: 9.3125,
 624: 13.5,
 626: 12.789473684210526,
 629: 14.8,
 630: 12.44,
 631: 17.272727272727273,
 632: 18.0,
 634: 16.4,
 635: 12.818181818181818,
 636: 12.0,
 637: 13.083333333333334,
 638: 13.61111111111111,
 641: 16.085714285714285,
 642: 10.5,
 643: 10.857142857142858,
 645: 13.5,
 646: 9.741935483870968,
 647: 16.88888888888889,
 649: 14.073170731707316,
 650: 10.642857142857142,
 651: 19.363636363636363,
 652: 14.454545454545455,
 653: 14.071428571428571,
 655: 14.826086956521738,
 657: 15.962962962962964,
 658: 14.571428571428571,
 660: 15.0,
 661: 13.666666666666666,
 662: 12.944444444444445,
 664: 13.333333333333334,
 665: 17.4,
 667: 13.532467532467532,
 668: 10.833333333333334,
 669: 10.64516129032258,
 670: 11.4,
 671: 16.5,
 672: 12.026315789473685,
 673: 16.166666666666668,
 675: 16.9,
 676: 19.0,
 677: 13.0,
 678: 15.8,
 679: 17.0,
 680: 22.0,
 681: 12.0,
 682: 13.0,
 683: 11.23076923076923,
 684: 11.4,
 687: 11.253164556962025,
 688: 10.170212765957446,
 690: 13.588888888888889,
 692: 11.285714285714286,
 693: 13.6,
 694: 11.0,
 696: 9.575757575757576,
 697: 9.0,
 698: 15.090909090909092,
 699: 11.283018867924529,
 700: 14.181818181818182,
 701: 13.0,
 702: 10.75,
 703: 13.0,
 704: 14.0,
 705: 11.142857142857142,
 706: 11.444444444444445,
 707: 14.5,
 709: 19.727272727272727,
 710: 12.857142857142858,
 711: 21.0,
 713: 13.142857142857142,
 714: 11.2,
 715: 14.0,
 717: 20.0,
 719: 11.94047619047619,
 720: 12.433333333333334,
 721: 13.409090909090908,
 722: 16.4,
 723: 11.178571428571429,
 725: 13.928571428571429,
 726: 16.5,
 727: 10.857142857142858,
 728: 12.851851851851851,
 729: 11.675675675675675,
 730: 10.0,
 731: 13.777777777777779,
 732: 14.375,
 734: 12.81578947368421,
 735: 11.882352941176471,
 737: 9.333333333333334,
 738: 10.833333333333334,
 740: 15.444444444444445,
 741: 15.733333333333333,
 742: 12.166666666666666,
 743: 16.333333333333332,
 745: 15.166666666666666,
 746: 18.5,
 747: 8.666666666666666,
 749: 14.25,
 751: 10.5,
 752: 12.88888888888889,
 754: 9.222222222222221,
 755: 11.461538461538462,
 756: 13.037037037037036,
 757: 16.142857142857142,
 758: 15.076923076923077,
 761: 13.625,
 762: 14.89795918367347,
 766: 11.692307692307692,
 767: 17.043478260869566,
 768: 12.969696969696969,
 769: 15.0,
 772: 9.75,
 773: 12.0,
 774: 12.0,
 775: 13.5,
 777: 10.5,
 778: 12.214285714285714,
 779: 11.125,
 780: 13.333333333333334,
 781: 9.0,
 784: 14.25,
 785: 12.0,
 786: 13.947916666666666,
 787: 14.466666666666667,
 789: 13.0,
 791: 12.0,
 792: 10.2,
 793: 11.333333333333334,
 794: 15.0,
 795: 14.25,
 796: 14.55,
 797: 14.1875,
 798: 14.2,
 799: 16.25,
 800: 15.285714285714286,
 801: 13.0,
 802: 14.11111111111111,
 803: 13.142857142857142,
 804: 12.75,
 806: 17.666666666666668,
 807: 13.4,
 809: 15.588235294117647,
 811: 17.428571428571427,
 812: 11.646341463414634,
 813: 8.0,
 817: 17.0,
 818: 14.15,
 823: 20.0,
 824: 14.454545454545455,
 825: 13.0,
 827: 12.571428571428571,
 830: 14.444444444444445,
 831: 14.454545454545455,
 832: 14.1,
 833: 14.5,
 834: 10.89655172413793,
 836: 22.0,
 838: 11.285714285714286,
 839: 15.19047619047619,
 840: 14.285714285714286,
 841: 11.38888888888889,
 842: 12.277777777777779,
 844: 12.0,
 845: 13.107142857142858,
 847: 14.492753623188406,
 848: 12.764705882352942,
 849: 16.22222222222222,
 850: 13.571428571428571,
 851: 13.222222222222221,
 852: 14.482142857142858,
 853: 9.1,
 854: 12.851851851851851,
 855: 14.823529411764707,
 857: 12.846153846153847,
 858: 12.666666666666666,
 859: 14.125,
 860: 12.705882352941176,
 862: 13.0,
 863: 14.782608695652174,
 864: 13.625,
 866: 14.327272727272728,
 867: 6.333333333333333,
 868: 12.56140350877193,
 870: 10.279411764705882,
 873: 9.5625,
 874: 16.294117647058822,
 877: 15.272727272727273,
 878: 16.0,
 879: 12.2,
 880: 13.935483870967742,
 881: 15.8,
 883: 12.666666666666666,
 885: 18.6,
 886: 13.823529411764707,
 887: 9.4,
 888: 14.8,
 889: 8.75,
 890: 16.791666666666668,
 891: 10.8,
 892: 17.928571428571427,
 893: 13.3,
 894: 13.163120567375886,
 895: 13.5,
 896: 13.261904761904763,
 898: 12.481481481481481,
 899: 16.333333333333332,
 900: 11.0,
 903: 13.333333333333334,
 904: 13.25,
 907: 13.5,
 908: 11.3,
 910: 11.0,
 911: 12.982142857142858,
 912: 14.5,
 913: 12.9375,
 914: 12.28125,
 915: 11.428571428571429,
 916: 12.666666666666666,
 917: 15.320754716981131,
 919: 12.090909090909092,
 921: 12.0,
 923: 21.0,
 924: 15.63888888888889,
 926: 8.0,
 928: 19.0,
 932: 17.636363636363637,
 933: 13.5,
 935: 13.470588235294118,
 936: 11.333333333333334,
 937: 16.714285714285715,
 938: 14.5,
 939: 14.75,
 940: 12.363636363636363,
 941: 13.5,
 942: 10.0,
 945: 14.666666666666666,
 946: 18.137931034482758,
 947: 14.564102564102564,
 948: 16.8,
 949: 11.0,
 950: 9.666666666666666,
 953: 10.75,
 954: 14.857142857142858,
 955: 18.5,
 956: 13.833333333333334,
 957: 12.409090909090908,
 958: 12.612244897959183,
 959: 18.615384615384617,
 960: 14.681818181818182,
 961: 13.875,
 962: 14.0,
 963: 12.064516129032258,
 964: 14.53968253968254,
 965: 14.0,
 966: 13.894736842105264,
 968: 13.25,
 969: 12.75,
 970: 23.0,
 971: 10.5,
 972: 10.366666666666667,
 973: 15.634146341463415,
 974: 10.571428571428571,
 975: 15.16,
 977: 12.538461538461538,
 978: 9.941176470588236,
 979: 17.0,
 980: 12.533333333333333,
 981: 14.166666666666666,
 982: 11.310344827586206,
 983: 14.5,
 984: 13.972972972972974,
 985: 14.0,
 986: 16.0,
 987: 12.25,
 990: 14.0,
 991: 16.0,
 992: 14.142857142857142,
 993: 9.454545454545455,
 994: 12.882352941176471,
 995: 12.806451612903226,
 997: 14.533333333333333,
 998: 13.583333333333334,
 999: 12.090909090909092,
 1000: 16.214285714285715,
 1001: 8.5,
 1002: 14.266666666666667,
 1003: 16.65,
 1004: 12.380530973451327,
 1005: 13.785714285714286,
 1007: 14.5,
 1008: 12.4,
 1009: 16.36,
 1011: 15.555555555555555,
 1012: 16.46153846153846,
 1013: 12.764705882352942,
 1015: 19.0,
 1016: 12.153846153846153,
 1017: 10.666666666666666,
 1018: 12.4375,
 1019: 10.090909090909092,
 1021: 13.305084745762711,
 1022: 15.081632653061224,
 1023: 11.708333333333334,
 1024: 12.0,
 1025: 14.4,
 1026: 10.0,
 1027: 13.576923076923077,
 1029: 9.25,
 1031: 15.0,
 1034: 11.5,
 1035: 15.172413793103448,
 1036: 11.678571428571429,
 1037: 15.071428571428571,
 1038: 14.470588235294118,
 1040: 17.714285714285715,
 1041: 15.466666666666667,
 1043: 13.333333333333334,
 1044: 15.384615384615385,
 1047: 11.380952380952381,
 1049: 15.375,
 1050: 14.538461538461538,
 1051: 9.333333333333334,
 1052: 16.166666666666668,
 1054: 11.4,
 1055: 12.96551724137931,
 1056: 12.32258064516129,
 1058: 4.538461538461538,
 1059: 12.156862745098039,
 1060: 8.5,
 1062: 11.833333333333334,
 1064: 11.857142857142858,
 1065: 13.0,
 1066: 12.115942028985508,
 1067: 14.75,
 1069: 16.555555555555557,
 1071: 16.75,
 1072: 13.368421052631579,
 1073: 17.333333333333332,
 1075: 10.877551020408163,
 1076: 12.75,
 1077: 12.266666666666667,
 1078: 11.833333333333334,
 1079: 14.6,
 1080: 12.75,
 1081: 13.0,
 1082: 18.5,
 1083: 16.636363636363637,
 1084: 14.1,
 1086: 13.0,
 1088: 15.647058823529411,
 1089: 18.27777777777778,
 1091: 14.0,
 1092: 14.5,
 1093: 12.8,
 1094: 12.0,
 1095: 17.452380952380953,
 1096: 15.142857142857142,
 1099: 12.0,
 1100: 14.142857142857142,
 1101: 8.5,
 1102: 9.0,
 1103: 12.0,
 1104: 13.0,
 1105: 10.11111111111111,
 1106: 13.0,
 1107: 14.163636363636364,
 1108: 10.75,
 1109: 12.823529411764707,
 1111: 10.444444444444445,
 1112: 13.916666666666666,
 1115: 14.0,
 1116: 13.777777777777779,
 1117: 16.333333333333332,
 1118: 14.375,
 1119: 11.666666666666666,
 1120: 12.291666666666666,
 1122: 12.666666666666666,
 1123: 11.5,
 1124: 12.5,
 1125: 13.666666666666666,
 1126: 15.6,
 1127: 12.0,
 1128: 16.333333333333332,
 1130: 9.37037037037037,
 1132: 9.454545454545455,
 1133: 19.0,
 1134: 13.444444444444445,
 1136: 14.67741935483871,
 1137: 12.357142857142858,
 1138: 12.736842105263158,
 1139: 13.8,
 1140: 13.0,
 1141: 11.55,
 1142: 15.1,
 1147: 12.76923076923077,
 1150: 13.487179487179487,
 1151: 11.294117647058824,
 1153: 12.428571428571429,
 1155: 15.0,
 1156: 13.6,
 1157: 15.454545454545455,
 1158: 15.666666666666666,
 1159: 18.0,
 1160: 13.2,
 1161: 9.666666666666666,
 1162: 13.0,
 1163: 14.166666666666666,
 1164: 15.220338983050848,
 1165: 13.235294117647058,
 1166: 13.5,
 1167: 15.0,
 1169: 13.125,
 1170: 13.857142857142858,
 1171: 15.142857142857142,
 1173: 12.30952380952381,
 1175: 15.0,
 1176: 11.75,
 1177: 15.68421052631579,
 1178: 12.5,
 1179: 12.6,
 1180: 12.25,
 1181: 11.5,
 1184: 12.0,
 1185: 11.166666666666666,
 1186: 13.952380952380953,
 1188: 15.214285714285714,
 1189: 9.833333333333334,
 1191: 10.916666666666666,
 1196: 15.181818181818182,
 1197: 11.734375,
 1198: 11.333333333333334,
 1199: 11.03225806451613,
 1201: 14.0,
 1202: 11.727272727272727,
 1203: 16.96,
 1204: 15.0,
 1206: 16.0,
 1208: 16.923076923076923,
 1209: 15.5,
 1210: 14.823529411764707,
 1212: 11.5,
 1213: 14.25,
 1214: 17.25,
 1215: 15.181818181818182,
 1216: 13.8,
 1217: 8.222222222222221,
 1219: 12.0,
 1220: 16.0,
 1221: 13.0,
 1224: 9.0,
 1225: 14.391304347826088,
 1226: 16.0,
 1231: 12.63888888888889,
 1232: 18.0,
 1233: 15.0,
 1234: 17.23076923076923,
 1235: 18.6,
 1236: 15.052631578947368,
 1237: 17.333333333333332,
 1238: 15.804878048780488,
 1240: 13.460674157303371,
 1241: 14.25,
 1242: 11.931818181818182,
 1243: 19.5,
 1244: 16.0,
 1245: 14.75,
 1246: 12.097560975609756,
 1247: 15.0,
 1249: 12.4,
 1250: 13.11111111111111,
 1251: 12.9,
 1252: 10.333333333333334,
 1253: 13.666666666666666,
 1254: 17.875,
 1255: 11.571428571428571,
 1256: 11.333333333333334,
 1258: 19.375,
 1259: 13.4,
 1260: 10.5,
 1261: 16.0,
 1263: 10.615384615384615,
 1264: 12.77659574468085,
 1266: 15.833333333333334,
 1267: 12.485714285714286,
 1268: 12.714285714285714,
 1269: 10.0,
 1270: 12.2,
 1271: 14.95,
 1272: 13.428571428571429,
 1274: 12.75,
 1275: 13.75,
 1276: 16.428571428571427,
 1277: 12.833333333333334,
 1279: 12.75,
 1280: 15.333333333333334,
 1281: 15.26086956521739,
 1283: 14.5,
 1284: 11.5,
 1285: 15.258064516129032,
 1286: 13.333333333333334,
 1287: 10.0,
 1288: 15.375,
 1290: 7.75,
 1291: 12.0,
 1292: 16.25,
 1293: 14.466666666666667,
 1295: 12.5,
 1296: 13.5,
 1297: 17.0,
 1298: 14.0,
 1299: 14.428571428571429,
 1300: 11.8,
 1301: 11.5,
 1303: 17.0,
 1305: 15.666666666666666,
 ...}

In [142]:
# populating 'hour_profile' with dictionary values

df['hour_avg'] = df['user_id'].map(df_order_hour.to_dict()['order_hour_of_day'])

In [157]:
# checking df output

df.tail()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,date_joined,n_dependants,fam_status,income,cust_merge,Region,Activity,Profile,hour_avg,Behavior_Profile
1014025,2641620,179940,4,wednesday,8,30.0,13544,6,0,3 Color Deli Coleslaw,...,11/1/2017,1,married,57053,both,West,high,(MP)(YA)(LI),9.272727,(MS)
26263917,1890094,195032,14,saturday,22,7.0,13227,17,1,Little Movers,...,2/11/2018,3,married,100370,both,South,high,(MP)(NP)(MA)(MI),15.957746,
29330090,714478,117297,9,wednesday,15,12.0,26131,5,1,Mixed Berries Whole Milk Icelandic Style Skyr ...,...,1/17/2020,3,married,54316,both,West,high,(MP)(YA)(LI),9.571429,(MS)
6968744,3393525,68065,6,monday,12,4.0,47766,10,1,Organic Avocado,...,5/4/2017,2,married,126907,both,South,high,(MP)(E)(MI),14.983607,
1403981,2665296,59164,3,thursday,11,18.0,12916,3,1,Ginger Ale,...,3/7/2020,1,married,85136,both,South,high,(MP)(YA)(MI),13.750000,

#### Creating profile flags

In [154]:
df['Behavior_Profile'] = ''

In [155]:
# creating flag for morning shopper

df.loc[(df['hour_avg'] >= 5) & (df['hour_avg'] <= 12) , 'Behavior_Profile'] = df['Behavior_Profile'] + '(MS)'

In [158]:
# creating flag for afternoon shopper

df.loc[(df['hour_avg'] > 12) & (df['hour_avg'] <= 17) , 'Behavior_Profile'] = df['Behavior_Profile'] + '(AS)'

In [160]:
# creating flag for evening shopper

df.loc[(df['hour_avg'] > 17) & (df['hour_avg'] <= 21) , 'Behavior_Profile'] = df['Behavior_Profile'] + '(ES)'

In [165]:
# creating flag for night shopper part 1

df.loc[(df['hour_avg'] > 21), 'Behavior_Profile'] = df['Behavior_Profile'] + '(NS)'

In [167]:
# creating flag for night shopper part 2

df.loc[(df['hour_avg'] < 5), 'Behavior_Profile'] = df['Behavior_Profile'] + '(NS)'

In [168]:
df['Behavior_Profile'].value_counts(dropna = False)

(AS)    2255166
(MS)     728301
(ES)     109983
(NS)       3006
Name: Behavior_Profile, dtype: int64

In [169]:
# checking a user_id

df[df['user_id'] == 1]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,date_joined,n_dependants,fam_status,income,cust_merge,Region,Activity,Profile,hour_avg,Behavior_Profile
1,2398795,1,2,tuesday,7,15.0,196,1,1,Soda,...,2/17/2019,3,married,40423,both,South,high,(MP)(YA)(LI),8.5,(MS)
29,3367565,1,6,monday,7,19.0,10258,3,1,Pistachios,...,2/17/2019,3,married,40423,both,South,high,(MP)(YA)(LI),8.5,(MS)
22,2398795,1,2,tuesday,7,15.0,26088,5,1,Aged White Cheddar Popcorn,...,2/17/2019,3,married,40423,both,South,high,(MP)(YA)(LI),8.5,(MS)
15,431534,1,5,wednesday,15,28.0,12427,2,1,Original Beef Jerky,...,2/17/2019,3,married,40423,both,South,high,(MP)(YA)(LI),8.5,(MS)
3,2254736,1,4,wednesday,7,29.0,196,1,1,Soda,...,2/17/2019,3,married,40423,both,South,high,(MP)(YA)(LI),8.5,(MS)
33,2550362,1,10,wednesday,8,30.0,10258,6,1,Pistachios,...,2/17/2019,3,married,40423,both,South,high,(MP)(YA)(LI),8.5,(MS)